#RETO IBM NGINX REVERSE PROXY DOCKERFILE - PAOLO CASASOLA ESTEBAN
FROM nginx:1.19.5-alpine
COPY ./nginx.conf /etc/nginx/nginx.conf
HEALTHCHECK --interval=5m --timeout=3s \
  CMD curl -f http://localhost/ || exit 1
