#RETOR IBM - PAOLO CASASOLA ESTEBAN

FROM node:15.4.0-alpine3.10

RUN mkdir /home/node/retoibm_backend

WORKDIR /home/node/retoibm_backend

COPY ./retobase-nodejs/* ./

RUN npm install

HEALTHCHECK --interval=10s --timeout=2s --retries=2 --start-period=15s CMD node healthcheck.js

EXPOSE 4000
